#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QlTourDuLich")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHANHTRINH(HANHTRINH instance);
    partial void UpdateHANHTRINH(HANHTRINH instance);
    partial void DeleteHANHTRINH(HANHTRINH instance);
    partial void InsertDIADIEM(DIADIEM instance);
    partial void UpdateDIADIEM(DIADIEM instance);
    partial void DeleteDIADIEM(DIADIEM instance);
    partial void InsertDIADANH(DIADANH instance);
    partial void UpdateDIADANH(DIADANH instance);
    partial void DeleteDIADANH(DIADANH instance);
    partial void InsertKHACHSAN(KHACHSAN instance);
    partial void UpdateKHACHSAN(KHACHSAN instance);
    partial void DeleteKHACHSAN(KHACHSAN instance);
    partial void InsertLOAIKHACHSAN(LOAIKHACHSAN instance);
    partial void UpdateLOAIKHACHSAN(LOAIKHACHSAN instance);
    partial void DeleteLOAIKHACHSAN(LOAIKHACHSAN instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Linq.Properties.Settings.Default.QlTourDuLichConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<HANHTRINH> HANHTRINHs
		{
			get
			{
				return this.GetTable<HANHTRINH>();
			}
		}
		
		public System.Data.Linq.Table<DIADIEM> DIADIEMs
		{
			get
			{
				return this.GetTable<DIADIEM>();
			}
		}
		
		public System.Data.Linq.Table<DIADANH> DIADANHs
		{
			get
			{
				return this.GetTable<DIADANH>();
			}
		}
		
		public System.Data.Linq.Table<KHACHSAN> KHACHSANs
		{
			get
			{
				return this.GetTable<KHACHSAN>();
			}
		}
		
		public System.Data.Linq.Table<LOAIKHACHSAN> LOAIKHACHSANs
		{
			get
			{
				return this.GetTable<LOAIKHACHSAN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HANHTRINH")]
	public partial class HANHTRINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHanhTrinh;
		
		private System.Nullable<int> _NoiDi;
		
		private System.Nullable<int> _NoiDen;
		
		private EntityRef<DIADIEM> _DIADIEM;
		
		private EntityRef<DIADIEM> _DIADIEM1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHanhTrinhChanging(string value);
    partial void OnMaHanhTrinhChanged();
    partial void OnNoiDiChanging(System.Nullable<int> value);
    partial void OnNoiDiChanged();
    partial void OnNoiDenChanging(System.Nullable<int> value);
    partial void OnNoiDenChanged();
    #endregion
		
		public HANHTRINH()
		{
			this._DIADIEM = default(EntityRef<DIADIEM>);
			this._DIADIEM1 = default(EntityRef<DIADIEM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHanhTrinh", DbType="VarChar(11) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHanhTrinh
		{
			get
			{
				return this._MaHanhTrinh;
			}
			set
			{
				if ((this._MaHanhTrinh != value))
				{
					this.OnMaHanhTrinhChanging(value);
					this.SendPropertyChanging();
					this._MaHanhTrinh = value;
					this.SendPropertyChanged("MaHanhTrinh");
					this.OnMaHanhTrinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDi", DbType="Int")]
		public System.Nullable<int> NoiDi
		{
			get
			{
				return this._NoiDi;
			}
			set
			{
				if ((this._NoiDi != value))
				{
					if (this._DIADIEM1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNoiDiChanging(value);
					this.SendPropertyChanging();
					this._NoiDi = value;
					this.SendPropertyChanged("NoiDi");
					this.OnNoiDiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDen", DbType="Int")]
		public System.Nullable<int> NoiDen
		{
			get
			{
				return this._NoiDen;
			}
			set
			{
				if ((this._NoiDen != value))
				{
					if (this._DIADIEM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNoiDenChanging(value);
					this.SendPropertyChanging();
					this._NoiDen = value;
					this.SendPropertyChanged("NoiDen");
					this.OnNoiDenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIADIEM_HANHTRINH", Storage="_DIADIEM", ThisKey="NoiDen", OtherKey="MaDiaDiem", IsForeignKey=true)]
		public DIADIEM DIADIEM
		{
			get
			{
				return this._DIADIEM.Entity;
			}
			set
			{
				DIADIEM previousValue = this._DIADIEM.Entity;
				if (((previousValue != value) 
							|| (this._DIADIEM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DIADIEM.Entity = null;
						previousValue.HANHTRINHs.Remove(this);
					}
					this._DIADIEM.Entity = value;
					if ((value != null))
					{
						value.HANHTRINHs.Add(this);
						this._NoiDen = value.MaDiaDiem;
					}
					else
					{
						this._NoiDen = default(Nullable<int>);
					}
					this.SendPropertyChanged("DIADIEM");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIADIEM_HANHTRINH1", Storage="_DIADIEM1", ThisKey="NoiDi", OtherKey="MaDiaDiem", IsForeignKey=true)]
		public DIADIEM DIADIEM1
		{
			get
			{
				return this._DIADIEM1.Entity;
			}
			set
			{
				DIADIEM previousValue = this._DIADIEM1.Entity;
				if (((previousValue != value) 
							|| (this._DIADIEM1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DIADIEM1.Entity = null;
						previousValue.HANHTRINHs1.Remove(this);
					}
					this._DIADIEM1.Entity = value;
					if ((value != null))
					{
						value.HANHTRINHs1.Add(this);
						this._NoiDi = value.MaDiaDiem;
					}
					else
					{
						this._NoiDi = default(Nullable<int>);
					}
					this.SendPropertyChanged("DIADIEM1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DIADIEM")]
	public partial class DIADIEM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDiaDiem;
		
		private string _TenDiaDiem;
		
		private string _MaDiaDanh;
		
		private EntitySet<HANHTRINH> _HANHTRINHs;
		
		private EntitySet<HANHTRINH> _HANHTRINHs1;
		
		private EntitySet<KHACHSAN> _KHACHSANs;
		
		private EntityRef<DIADANH> _DIADANH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDiaDiemChanging(int value);
    partial void OnMaDiaDiemChanged();
    partial void OnTenDiaDiemChanging(string value);
    partial void OnTenDiaDiemChanged();
    partial void OnMaDiaDanhChanging(string value);
    partial void OnMaDiaDanhChanged();
    #endregion
		
		public DIADIEM()
		{
			this._HANHTRINHs = new EntitySet<HANHTRINH>(new Action<HANHTRINH>(this.attach_HANHTRINHs), new Action<HANHTRINH>(this.detach_HANHTRINHs));
			this._HANHTRINHs1 = new EntitySet<HANHTRINH>(new Action<HANHTRINH>(this.attach_HANHTRINHs1), new Action<HANHTRINH>(this.detach_HANHTRINHs1));
			this._KHACHSANs = new EntitySet<KHACHSAN>(new Action<KHACHSAN>(this.attach_KHACHSANs), new Action<KHACHSAN>(this.detach_KHACHSANs));
			this._DIADANH = default(EntityRef<DIADANH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDiaDiem", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDiaDiem
		{
			get
			{
				return this._MaDiaDiem;
			}
			set
			{
				if ((this._MaDiaDiem != value))
				{
					this.OnMaDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._MaDiaDiem = value;
					this.SendPropertyChanged("MaDiaDiem");
					this.OnMaDiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDiaDiem", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenDiaDiem
		{
			get
			{
				return this._TenDiaDiem;
			}
			set
			{
				if ((this._TenDiaDiem != value))
				{
					this.OnTenDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._TenDiaDiem = value;
					this.SendPropertyChanged("TenDiaDiem");
					this.OnTenDiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDiaDanh", DbType="VarChar(10)")]
		public string MaDiaDanh
		{
			get
			{
				return this._MaDiaDanh;
			}
			set
			{
				if ((this._MaDiaDanh != value))
				{
					if (this._DIADANH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDiaDanhChanging(value);
					this.SendPropertyChanging();
					this._MaDiaDanh = value;
					this.SendPropertyChanged("MaDiaDanh");
					this.OnMaDiaDanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIADIEM_HANHTRINH", Storage="_HANHTRINHs", ThisKey="MaDiaDiem", OtherKey="NoiDen")]
		public EntitySet<HANHTRINH> HANHTRINHs
		{
			get
			{
				return this._HANHTRINHs;
			}
			set
			{
				this._HANHTRINHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIADIEM_HANHTRINH1", Storage="_HANHTRINHs1", ThisKey="MaDiaDiem", OtherKey="NoiDi")]
		public EntitySet<HANHTRINH> HANHTRINHs1
		{
			get
			{
				return this._HANHTRINHs1;
			}
			set
			{
				this._HANHTRINHs1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIADIEM_KHACHSAN", Storage="_KHACHSANs", ThisKey="MaDiaDiem", OtherKey="MaDiaDiem")]
		public EntitySet<KHACHSAN> KHACHSANs
		{
			get
			{
				return this._KHACHSANs;
			}
			set
			{
				this._KHACHSANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIADANH_DIADIEM", Storage="_DIADANH", ThisKey="MaDiaDanh", OtherKey="MaDiaDanh", IsForeignKey=true)]
		public DIADANH DIADANH
		{
			get
			{
				return this._DIADANH.Entity;
			}
			set
			{
				DIADANH previousValue = this._DIADANH.Entity;
				if (((previousValue != value) 
							|| (this._DIADANH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DIADANH.Entity = null;
						previousValue.DIADIEMs.Remove(this);
					}
					this._DIADANH.Entity = value;
					if ((value != null))
					{
						value.DIADIEMs.Add(this);
						this._MaDiaDanh = value.MaDiaDanh;
					}
					else
					{
						this._MaDiaDanh = default(string);
					}
					this.SendPropertyChanged("DIADANH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HANHTRINHs(HANHTRINH entity)
		{
			this.SendPropertyChanging();
			entity.DIADIEM = this;
		}
		
		private void detach_HANHTRINHs(HANHTRINH entity)
		{
			this.SendPropertyChanging();
			entity.DIADIEM = null;
		}
		
		private void attach_HANHTRINHs1(HANHTRINH entity)
		{
			this.SendPropertyChanging();
			entity.DIADIEM1 = this;
		}
		
		private void detach_HANHTRINHs1(HANHTRINH entity)
		{
			this.SendPropertyChanging();
			entity.DIADIEM1 = null;
		}
		
		private void attach_KHACHSANs(KHACHSAN entity)
		{
			this.SendPropertyChanging();
			entity.DIADIEM = this;
		}
		
		private void detach_KHACHSANs(KHACHSAN entity)
		{
			this.SendPropertyChanging();
			entity.DIADIEM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DIADANH")]
	public partial class DIADANH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDiaDanh;
		
		private string _TenDiaDanh;
		
		private EntitySet<DIADIEM> _DIADIEMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDiaDanhChanging(string value);
    partial void OnMaDiaDanhChanged();
    partial void OnTenDiaDanhChanging(string value);
    partial void OnTenDiaDanhChanged();
    #endregion
		
		public DIADANH()
		{
			this._DIADIEMs = new EntitySet<DIADIEM>(new Action<DIADIEM>(this.attach_DIADIEMs), new Action<DIADIEM>(this.detach_DIADIEMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDiaDanh", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDiaDanh
		{
			get
			{
				return this._MaDiaDanh;
			}
			set
			{
				if ((this._MaDiaDanh != value))
				{
					this.OnMaDiaDanhChanging(value);
					this.SendPropertyChanging();
					this._MaDiaDanh = value;
					this.SendPropertyChanged("MaDiaDanh");
					this.OnMaDiaDanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDiaDanh", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenDiaDanh
		{
			get
			{
				return this._TenDiaDanh;
			}
			set
			{
				if ((this._TenDiaDanh != value))
				{
					this.OnTenDiaDanhChanging(value);
					this.SendPropertyChanging();
					this._TenDiaDanh = value;
					this.SendPropertyChanged("TenDiaDanh");
					this.OnTenDiaDanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIADANH_DIADIEM", Storage="_DIADIEMs", ThisKey="MaDiaDanh", OtherKey="MaDiaDanh")]
		public EntitySet<DIADIEM> DIADIEMs
		{
			get
			{
				return this._DIADIEMs;
			}
			set
			{
				this._DIADIEMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DIADIEMs(DIADIEM entity)
		{
			this.SendPropertyChanging();
			entity.DIADANH = this;
		}
		
		private void detach_DIADIEMs(DIADIEM entity)
		{
			this.SendPropertyChanging();
			entity.DIADANH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHSAN")]
	public partial class KHACHSAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKS;
		
		private string _TenKS;
		
		private string _MaLoaiKS;
		
		private System.Nullable<int> _MaDiaDiem;
		
		private System.Nullable<decimal> _GiaTien;
		
		private EntityRef<DIADIEM> _DIADIEM;
		
		private EntityRef<LOAIKHACHSAN> _LOAIKHACHSAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKSChanging(string value);
    partial void OnMaKSChanged();
    partial void OnTenKSChanging(string value);
    partial void OnTenKSChanged();
    partial void OnMaLoaiKSChanging(string value);
    partial void OnMaLoaiKSChanged();
    partial void OnMaDiaDiemChanging(System.Nullable<int> value);
    partial void OnMaDiaDiemChanged();
    partial void OnGiaTienChanging(System.Nullable<decimal> value);
    partial void OnGiaTienChanged();
    #endregion
		
		public KHACHSAN()
		{
			this._DIADIEM = default(EntityRef<DIADIEM>);
			this._LOAIKHACHSAN = default(EntityRef<LOAIKHACHSAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKS", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKS
		{
			get
			{
				return this._MaKS;
			}
			set
			{
				if ((this._MaKS != value))
				{
					this.OnMaKSChanging(value);
					this.SendPropertyChanging();
					this._MaKS = value;
					this.SendPropertyChanged("MaKS");
					this.OnMaKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKS", DbType="NVarChar(50)")]
		public string TenKS
		{
			get
			{
				return this._TenKS;
			}
			set
			{
				if ((this._TenKS != value))
				{
					this.OnTenKSChanging(value);
					this.SendPropertyChanging();
					this._TenKS = value;
					this.SendPropertyChanged("TenKS");
					this.OnTenKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiKS", DbType="VarChar(10)")]
		public string MaLoaiKS
		{
			get
			{
				return this._MaLoaiKS;
			}
			set
			{
				if ((this._MaLoaiKS != value))
				{
					if (this._LOAIKHACHSAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiKSChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiKS = value;
					this.SendPropertyChanged("MaLoaiKS");
					this.OnMaLoaiKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDiaDiem", DbType="Int")]
		public System.Nullable<int> MaDiaDiem
		{
			get
			{
				return this._MaDiaDiem;
			}
			set
			{
				if ((this._MaDiaDiem != value))
				{
					if (this._DIADIEM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._MaDiaDiem = value;
					this.SendPropertyChanged("MaDiaDiem");
					this.OnMaDiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTien", DbType="Money")]
		public System.Nullable<decimal> GiaTien
		{
			get
			{
				return this._GiaTien;
			}
			set
			{
				if ((this._GiaTien != value))
				{
					this.OnGiaTienChanging(value);
					this.SendPropertyChanging();
					this._GiaTien = value;
					this.SendPropertyChanged("GiaTien");
					this.OnGiaTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIADIEM_KHACHSAN", Storage="_DIADIEM", ThisKey="MaDiaDiem", OtherKey="MaDiaDiem", IsForeignKey=true)]
		public DIADIEM DIADIEM
		{
			get
			{
				return this._DIADIEM.Entity;
			}
			set
			{
				DIADIEM previousValue = this._DIADIEM.Entity;
				if (((previousValue != value) 
							|| (this._DIADIEM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DIADIEM.Entity = null;
						previousValue.KHACHSANs.Remove(this);
					}
					this._DIADIEM.Entity = value;
					if ((value != null))
					{
						value.KHACHSANs.Add(this);
						this._MaDiaDiem = value.MaDiaDiem;
					}
					else
					{
						this._MaDiaDiem = default(Nullable<int>);
					}
					this.SendPropertyChanged("DIADIEM");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIKHACHSAN_KHACHSAN", Storage="_LOAIKHACHSAN", ThisKey="MaLoaiKS", OtherKey="MaLoaiKS", IsForeignKey=true)]
		public LOAIKHACHSAN LOAIKHACHSAN
		{
			get
			{
				return this._LOAIKHACHSAN.Entity;
			}
			set
			{
				LOAIKHACHSAN previousValue = this._LOAIKHACHSAN.Entity;
				if (((previousValue != value) 
							|| (this._LOAIKHACHSAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIKHACHSAN.Entity = null;
						previousValue.KHACHSANs.Remove(this);
					}
					this._LOAIKHACHSAN.Entity = value;
					if ((value != null))
					{
						value.KHACHSANs.Add(this);
						this._MaLoaiKS = value.MaLoaiKS;
					}
					else
					{
						this._MaLoaiKS = default(string);
					}
					this.SendPropertyChanged("LOAIKHACHSAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIKHACHSAN")]
	public partial class LOAIKHACHSAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoaiKS;
		
		private string _TenLoaiKS;
		
		private EntitySet<KHACHSAN> _KHACHSANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiKSChanging(string value);
    partial void OnMaLoaiKSChanged();
    partial void OnTenLoaiKSChanging(string value);
    partial void OnTenLoaiKSChanged();
    #endregion
		
		public LOAIKHACHSAN()
		{
			this._KHACHSANs = new EntitySet<KHACHSAN>(new Action<KHACHSAN>(this.attach_KHACHSANs), new Action<KHACHSAN>(this.detach_KHACHSANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiKS", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiKS
		{
			get
			{
				return this._MaLoaiKS;
			}
			set
			{
				if ((this._MaLoaiKS != value))
				{
					this.OnMaLoaiKSChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiKS = value;
					this.SendPropertyChanged("MaLoaiKS");
					this.OnMaLoaiKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiKS", DbType="NVarChar(50)")]
		public string TenLoaiKS
		{
			get
			{
				return this._TenLoaiKS;
			}
			set
			{
				if ((this._TenLoaiKS != value))
				{
					this.OnTenLoaiKSChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiKS = value;
					this.SendPropertyChanged("TenLoaiKS");
					this.OnTenLoaiKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIKHACHSAN_KHACHSAN", Storage="_KHACHSANs", ThisKey="MaLoaiKS", OtherKey="MaLoaiKS")]
		public EntitySet<KHACHSAN> KHACHSANs
		{
			get
			{
				return this._KHACHSANs;
			}
			set
			{
				this._KHACHSANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KHACHSANs(KHACHSAN entity)
		{
			this.SendPropertyChanging();
			entity.LOAIKHACHSAN = this;
		}
		
		private void detach_KHACHSANs(KHACHSAN entity)
		{
			this.SendPropertyChanging();
			entity.LOAIKHACHSAN = null;
		}
	}
}
#pragma warning restore 1591
