//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HUONGDANVIEN
    {
        public HUONGDANVIEN()
        {
            this.TOURs = new HashSet<TOUR>();
        }
    
        public int MaHDV { get; set; }
        public string TenHDV { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string AnhDaiDien { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayVaoLam { get; set; }
        public string NgonNgu { get; set; }
    
        public virtual ICollection<TOUR> TOURs { get; set; }
    }
}
