//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANHTRINH
    {
        public HANHTRINH()
        {
            this.TOURs = new HashSet<TOUR>();
        }
    
        public string MAHANTRINH { get; set; }
        public string NOIDI { get; set; }
        public string NOIDEN { get; set; }
    
        public virtual DIADIEM DIADIEM { get; set; }
        public virtual DIADIEM DIADIEM1 { get; set; }
        public virtual ICollection<TOUR> TOURs { get; set; }
    }
}
