//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOPDONG
    {
        public string MATOUR { get; set; }
        public string MAHOPDONG { get; set; }
        public string TINHTRANG { get; set; }
        public string GHICHU { get; set; }
        public string MACT_HOPDONG { get; set; }
    
        public virtual HOPDONG HOPDONG { get; set; }
        public virtual TOUR TOUR { get; set; }
    }
}
