//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHopDong
    {
        public string MaCT_HopDong { get; set; }
        public string MaHopDong { get; set; }
        public string MaTour { get; set; }
        public Nullable<int> SLTreEm { get; set; }
        public Nullable<int> SLNguoiLon { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual HOPDONG HOPDONG { get; set; }
        public virtual TOUR TOUR { get; set; }
    }
}
