//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPHIEUNHAP_TOUR
    {
        public int Ma_CTPNhap { get; set; }
        public string MaTour { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string MaPNhap { get; set; }
    
        public virtual PHIEUNHAPTOUR PHIEUNHAPTOUR { get; set; }
        public virtual TOUR TOUR { get; set; }
    }
}
