//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIADIEM
    {
        public DIADIEM()
        {
            this.HANHTRINHs = new HashSet<HANHTRINH>();
            this.HANHTRINHs1 = new HashSet<HANHTRINH>();
            this.KHACHSANs = new HashSet<KHACHSAN>();
        }
    
        public int MaDiaDiem { get; set; }
        public string TenDiaDiem { get; set; }
        public string MaDiaDanh { get; set; }
    
        public virtual DIADANH DIADANH { get; set; }
        public virtual ICollection<HANHTRINH> HANHTRINHs { get; set; }
        public virtual ICollection<HANHTRINH> HANHTRINHs1 { get; set; }
        public virtual ICollection<KHACHSAN> KHACHSANs { get; set; }
    }
}
