//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIADANH
    {
        public int MaDiaDanh { get; set; }
        public string TenDiaDanh { get; set; }
        public Nullable<int> MaDiaDiem { get; set; }
    
        public virtual DIADIEM DIADIEM { get; set; }
    }
}
