//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHSAN
    {
        public KHACHSAN()
        {
            this.TOURs = new HashSet<TOUR>();
        }
    
        public string MaKS { get; set; }
        public string TenKS { get; set; }
        public string MaLoaiKS { get; set; }
        public Nullable<int> MaDiaDiem { get; set; }
        public Nullable<decimal> GiaTien { get; set; }
    
        public virtual DIADIEM DIADIEM { get; set; }
        public virtual LOAIKHACHSAN LOAIKHACHSAN { get; set; }
        public virtual ICollection<TOUR> TOURs { get; set; }
    }
}
