//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHSAN
    {
        public KHACHSAN()
        {
            this.HOPDONGs = new HashSet<HOPDONG>();
        }
    
        public string MAKHACHSAN { get; set; }
        public string MADIADIEM { get; set; }
        public string MALOAIKS { get; set; }
        public string TENKHACHSAN { get; set; }
        public decimal GIATIEN { get; set; }
    
        public virtual DIADIEM DIADIEM { get; set; }
        public virtual ICollection<HOPDONG> HOPDONGs { get; set; }
        public virtual LOAIKHACHSAN LOAIKHACHSAN { get; set; }
    }
}
