//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANHINH
    {
        public MANHINH()
        {
            this.PHANQUYENs = new HashSet<PHANQUYEN>();
        }
    
        public int MaMH { get; set; }
        public string TenMH { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<PHANQUYEN> PHANQUYENs { get; set; }
    }
}
