//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDUNG
    {
        public NGUOIDUNG()
        {
            this.QUANLINHOMNGUOIDUNGs = new HashSet<QUANLINHOMNGUOIDUNG>();
        }
    
        public string TENDANGNHAP { get; set; }
        public string MATKHAU { get; set; }
        public Nullable<bool> HOATDONG { get; set; }
    
        public virtual ICollection<QUANLINHOMNGUOIDUNG> QUANLINHOMNGUOIDUNGs { get; set; }
    }
}
