//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHOMNGUOIDUNG
    {
        public NHOMNGUOIDUNG()
        {
            this.NGUOIDUNGs = new HashSet<NGUOIDUNG>();
            this.PHANQUYENs = new HashSet<PHANQUYEN>();
            this.QUANLINHOMNGUOIDUNGs = new HashSet<QUANLINHOMNGUOIDUNG>();
        }
    
        public int MaNhom { get; set; }
        public string TenNhom { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<NGUOIDUNG> NGUOIDUNGs { get; set; }
        public virtual ICollection<PHANQUYEN> PHANQUYENs { get; set; }
        public virtual ICollection<QUANLINHOMNGUOIDUNG> QUANLINHOMNGUOIDUNGs { get; set; }
    }
}
