//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHOMNGUOIDUNG
    {
        public NHOMNGUOIDUNG()
        {
            this.PHANQUYENs = new HashSet<PHANQUYEN>();
            this.QUANLINHOMNGUOIDUNGs = new HashSet<QUANLINHOMNGUOIDUNG>();
        }
    
        public string MANHOM { get; set; }
        public string TENNHOM { get; set; }
        public string GHICHU { get; set; }
    
        public virtual ICollection<PHANQUYEN> PHANQUYENs { get; set; }
        public virtual ICollection<QUANLINHOMNGUOIDUNG> QUANLINHOMNGUOIDUNGs { get; set; }
    }
}
