//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR
    {
        public TOUR()
        {
            this.ChiTietHopDongs = new HashSet<ChiTietHopDong>();
            this.CTPHIEUNHAP_TOUR = new HashSet<CTPHIEUNHAP_TOUR>();
        }
    
        public string MaTour { get; set; }
        public string MaKS { get; set; }
        public string TenTour { get; set; }
        public Nullable<System.DateTime> NgayKhoiHanh { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<decimal> GiaTreEm { get; set; }
        public Nullable<decimal> GiaNguoiLon { get; set; }
        public string MoTa { get; set; }
        public string MaLoaiTour { get; set; }
        public string MaHanhTrinh { get; set; }
        public Nullable<int> MaHDV { get; set; }
        public string AnhDaiDien { get; set; }
        public Nullable<int> SoLuongDuKhach { get; set; }
    
        public virtual ICollection<ChiTietHopDong> ChiTietHopDongs { get; set; }
        public virtual ICollection<CTPHIEUNHAP_TOUR> CTPHIEUNHAP_TOUR { get; set; }
        public virtual HANHTRINH HANHTRINH { get; set; }
        public virtual HUONGDANVIEN HUONGDANVIEN { get; set; }
        public virtual KHACHSAN KHACHSAN { get; set; }
        public virtual LOAITOUR LOAITOUR { get; set; }
    }
}
