//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHSAN
    {
        public KHACHSAN()
        {
            this.TBLHOPDONGs = new HashSet<TBLHOPDONG>();
        }
    
        public string MAKHACHSAN { get; set; }
        public string MALOAIKS { get; set; }
        public string TENKHACHSAN { get; set; }
    
        public virtual TBLLOAIKHACHSAN TBLLOAIKHACHSAN { get; set; }
        public virtual ICollection<TBLHOPDONG> TBLHOPDONGs { get; set; }
    }
}
