//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_TourdulichEntities : DbContext
    {
        public QL_TourdulichEntities()
            : base("name=QL_TourdulichEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<KHACHSAN> KHACHSANs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TBLDIADANH> TBLDIADANHs { get; set; }
        public DbSet<TBLDIADIEM> TBLDIADIEMs { get; set; }
        public DbSet<TBLHANHTRINH> TBLHANHTRINHs { get; set; }
        public DbSet<TBLHOPDONG> TBLHOPDONGs { get; set; }
        public DbSet<TBLKHACHHANG> TBLKHACHHANGs { get; set; }
        public DbSet<TBLLOAIKHACH> TBLLOAIKHACHes { get; set; }
        public DbSet<TBLLOAIKHACHSAN> TBLLOAIKHACHSANs { get; set; }
        public DbSet<TBLLOAITOUR> TBLLOAITOURs { get; set; }
        public DbSet<TBLTOUR> TBLTOURs { get; set; }
    }
}
