//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("QL_TourdulichModel", "FK_KHACHSAN_RELATIONS_TBLLOAIK", "TBLLOAIKHACHSAN", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAO.TBLLOAIKHACHSAN), "KHACHSAN", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAO.KHACHSAN), true)]
[assembly: EdmRelationshipAttribute("QL_TourdulichModel", "FK_TBLHOPDO_RELATIONS_KHACHSAN", "KHACHSAN", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAO.KHACHSAN), "TBLHOPDONG", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAO.TBLHOPDONG), true)]
[assembly: EdmRelationshipAttribute("QL_TourdulichModel", "FK_TBLDIADA_RELATIONS_TBLDIADI", "TBLDIADIEM", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAO.TBLDIADIEM), "TBLDIADANH", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAO.TBLDIADANH), true)]
[assembly: EdmRelationshipAttribute("QL_TourdulichModel", "FK_TBLTOUR_RELATIONS_TBLHANHT", "TBLHANHTRINH", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAO.TBLHANHTRINH), "TBLTOUR", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAO.TBLTOUR), true)]
[assembly: EdmRelationshipAttribute("QL_TourdulichModel", "FK_TBLHOPDO_RELATIONS_TBLKHACH", "TBLKHACHHANG", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAO.TBLKHACHHANG), "TBLHOPDONG", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAO.TBLHOPDONG), true)]
[assembly: EdmRelationshipAttribute("QL_TourdulichModel", "FK_TBLKHACH_RELATIONS_TBLLOAIK", "TBLLOAIKHACH", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAO.TBLLOAIKHACH), "TBLKHACHHANG", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAO.TBLKHACHHANG), true)]
[assembly: EdmRelationshipAttribute("QL_TourdulichModel", "FK_TBLTOUR_RELATIONS_TBLLOAIT", "TBLLOAITOUR", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAO.TBLLOAITOUR), "TBLTOUR", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAO.TBLTOUR), true)]
[assembly: EdmRelationshipAttribute("QL_TourdulichModel", "CHITIETHANHTRINH", "TBLDIADIEM", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAO.TBLDIADIEM), "TBLHANHTRINH", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAO.TBLHANHTRINH))]
[assembly: EdmRelationshipAttribute("QL_TourdulichModel", "TBLCHIHOPDONG", "TBLHOPDONG", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAO.TBLHOPDONG), "TBLTOUR", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAO.TBLTOUR))]

#endregion

namespace DAO
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class QL_TourdulichEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new QL_TourdulichEntities object using the connection string found in the 'QL_TourdulichEntities' section of the application configuration file.
        /// </summary>
        public QL_TourdulichEntities() : base("name=QL_TourdulichEntities", "QL_TourdulichEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QL_TourdulichEntities object.
        /// </summary>
        public QL_TourdulichEntities(string connectionString) : base(connectionString, "QL_TourdulichEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QL_TourdulichEntities object.
        /// </summary>
        public QL_TourdulichEntities(EntityConnection connection) : base(connection, "QL_TourdulichEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<KHACHSAN> KHACHSANs
        {
            get
            {
                if ((_KHACHSANs == null))
                {
                    _KHACHSANs = base.CreateObjectSet<KHACHSAN>("KHACHSANs");
                }
                return _KHACHSANs;
            }
        }
        private ObjectSet<KHACHSAN> _KHACHSANs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TBLDIADANH> TBLDIADANHs
        {
            get
            {
                if ((_TBLDIADANHs == null))
                {
                    _TBLDIADANHs = base.CreateObjectSet<TBLDIADANH>("TBLDIADANHs");
                }
                return _TBLDIADANHs;
            }
        }
        private ObjectSet<TBLDIADANH> _TBLDIADANHs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TBLDIADIEM> TBLDIADIEMs
        {
            get
            {
                if ((_TBLDIADIEMs == null))
                {
                    _TBLDIADIEMs = base.CreateObjectSet<TBLDIADIEM>("TBLDIADIEMs");
                }
                return _TBLDIADIEMs;
            }
        }
        private ObjectSet<TBLDIADIEM> _TBLDIADIEMs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TBLHANHTRINH> TBLHANHTRINHs
        {
            get
            {
                if ((_TBLHANHTRINHs == null))
                {
                    _TBLHANHTRINHs = base.CreateObjectSet<TBLHANHTRINH>("TBLHANHTRINHs");
                }
                return _TBLHANHTRINHs;
            }
        }
        private ObjectSet<TBLHANHTRINH> _TBLHANHTRINHs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TBLHOPDONG> TBLHOPDONGs
        {
            get
            {
                if ((_TBLHOPDONGs == null))
                {
                    _TBLHOPDONGs = base.CreateObjectSet<TBLHOPDONG>("TBLHOPDONGs");
                }
                return _TBLHOPDONGs;
            }
        }
        private ObjectSet<TBLHOPDONG> _TBLHOPDONGs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TBLKHACHHANG> TBLKHACHHANGs
        {
            get
            {
                if ((_TBLKHACHHANGs == null))
                {
                    _TBLKHACHHANGs = base.CreateObjectSet<TBLKHACHHANG>("TBLKHACHHANGs");
                }
                return _TBLKHACHHANGs;
            }
        }
        private ObjectSet<TBLKHACHHANG> _TBLKHACHHANGs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TBLLOAIKHACH> TBLLOAIKHACHes
        {
            get
            {
                if ((_TBLLOAIKHACHes == null))
                {
                    _TBLLOAIKHACHes = base.CreateObjectSet<TBLLOAIKHACH>("TBLLOAIKHACHes");
                }
                return _TBLLOAIKHACHes;
            }
        }
        private ObjectSet<TBLLOAIKHACH> _TBLLOAIKHACHes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TBLLOAIKHACHSAN> TBLLOAIKHACHSANs
        {
            get
            {
                if ((_TBLLOAIKHACHSANs == null))
                {
                    _TBLLOAIKHACHSANs = base.CreateObjectSet<TBLLOAIKHACHSAN>("TBLLOAIKHACHSANs");
                }
                return _TBLLOAIKHACHSANs;
            }
        }
        private ObjectSet<TBLLOAIKHACHSAN> _TBLLOAIKHACHSANs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TBLLOAITOUR> TBLLOAITOURs
        {
            get
            {
                if ((_TBLLOAITOURs == null))
                {
                    _TBLLOAITOURs = base.CreateObjectSet<TBLLOAITOUR>("TBLLOAITOURs");
                }
                return _TBLLOAITOURs;
            }
        }
        private ObjectSet<TBLLOAITOUR> _TBLLOAITOURs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TBLTOUR> TBLTOURs
        {
            get
            {
                if ((_TBLTOURs == null))
                {
                    _TBLTOURs = base.CreateObjectSet<TBLTOUR>("TBLTOURs");
                }
                return _TBLTOURs;
            }
        }
        private ObjectSet<TBLTOUR> _TBLTOURs;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the KHACHSANs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKHACHSANs(KHACHSAN kHACHSAN)
        {
            base.AddObject("KHACHSANs", kHACHSAN);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TBLDIADANHs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTBLDIADANHs(TBLDIADANH tBLDIADANH)
        {
            base.AddObject("TBLDIADANHs", tBLDIADANH);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TBLDIADIEMs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTBLDIADIEMs(TBLDIADIEM tBLDIADIEM)
        {
            base.AddObject("TBLDIADIEMs", tBLDIADIEM);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TBLHANHTRINHs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTBLHANHTRINHs(TBLHANHTRINH tBLHANHTRINH)
        {
            base.AddObject("TBLHANHTRINHs", tBLHANHTRINH);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TBLHOPDONGs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTBLHOPDONGs(TBLHOPDONG tBLHOPDONG)
        {
            base.AddObject("TBLHOPDONGs", tBLHOPDONG);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TBLKHACHHANGs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTBLKHACHHANGs(TBLKHACHHANG tBLKHACHHANG)
        {
            base.AddObject("TBLKHACHHANGs", tBLKHACHHANG);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TBLLOAIKHACHes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTBLLOAIKHACHes(TBLLOAIKHACH tBLLOAIKHACH)
        {
            base.AddObject("TBLLOAIKHACHes", tBLLOAIKHACH);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TBLLOAIKHACHSANs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTBLLOAIKHACHSANs(TBLLOAIKHACHSAN tBLLOAIKHACHSAN)
        {
            base.AddObject("TBLLOAIKHACHSANs", tBLLOAIKHACHSAN);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TBLLOAITOURs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTBLLOAITOURs(TBLLOAITOUR tBLLOAITOUR)
        {
            base.AddObject("TBLLOAITOURs", tBLLOAITOUR);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TBLTOURs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTBLTOURs(TBLTOUR tBLTOUR)
        {
            base.AddObject("TBLTOURs", tBLTOUR);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QL_TourdulichModel", Name="KHACHSAN")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class KHACHSAN : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new KHACHSAN object.
        /// </summary>
        /// <param name="mAKHACHSAN">Initial value of the MAKHACHSAN property.</param>
        /// <param name="mALOAIKS">Initial value of the MALOAIKS property.</param>
        public static KHACHSAN CreateKHACHSAN(global::System.String mAKHACHSAN, global::System.String mALOAIKS)
        {
            KHACHSAN kHACHSAN = new KHACHSAN();
            kHACHSAN.MAKHACHSAN = mAKHACHSAN;
            kHACHSAN.MALOAIKS = mALOAIKS;
            return kHACHSAN;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MAKHACHSAN
        {
            get
            {
                return _MAKHACHSAN;
            }
            set
            {
                if (_MAKHACHSAN != value)
                {
                    OnMAKHACHSANChanging(value);
                    ReportPropertyChanging("MAKHACHSAN");
                    _MAKHACHSAN = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MAKHACHSAN");
                    OnMAKHACHSANChanged();
                }
            }
        }
        private global::System.String _MAKHACHSAN;
        partial void OnMAKHACHSANChanging(global::System.String value);
        partial void OnMAKHACHSANChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MALOAIKS
        {
            get
            {
                return _MALOAIKS;
            }
            set
            {
                OnMALOAIKSChanging(value);
                ReportPropertyChanging("MALOAIKS");
                _MALOAIKS = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MALOAIKS");
                OnMALOAIKSChanged();
            }
        }
        private global::System.String _MALOAIKS;
        partial void OnMALOAIKSChanging(global::System.String value);
        partial void OnMALOAIKSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TENKHACHSAN
        {
            get
            {
                return _TENKHACHSAN;
            }
            set
            {
                OnTENKHACHSANChanging(value);
                ReportPropertyChanging("TENKHACHSAN");
                _TENKHACHSAN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TENKHACHSAN");
                OnTENKHACHSANChanged();
            }
        }
        private global::System.String _TENKHACHSAN;
        partial void OnTENKHACHSANChanging(global::System.String value);
        partial void OnTENKHACHSANChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QL_TourdulichModel", "FK_KHACHSAN_RELATIONS_TBLLOAIK", "TBLLOAIKHACHSAN")]
        public TBLLOAIKHACHSAN TBLLOAIKHACHSAN
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLLOAIKHACHSAN>("QL_TourdulichModel.FK_KHACHSAN_RELATIONS_TBLLOAIK", "TBLLOAIKHACHSAN").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLLOAIKHACHSAN>("QL_TourdulichModel.FK_KHACHSAN_RELATIONS_TBLLOAIK", "TBLLOAIKHACHSAN").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TBLLOAIKHACHSAN> TBLLOAIKHACHSANReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLLOAIKHACHSAN>("QL_TourdulichModel.FK_KHACHSAN_RELATIONS_TBLLOAIK", "TBLLOAIKHACHSAN");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TBLLOAIKHACHSAN>("QL_TourdulichModel.FK_KHACHSAN_RELATIONS_TBLLOAIK", "TBLLOAIKHACHSAN", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QL_TourdulichModel", "FK_TBLHOPDO_RELATIONS_KHACHSAN", "TBLHOPDONG")]
        public EntityCollection<TBLHOPDONG> TBLHOPDONGs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TBLHOPDONG>("QL_TourdulichModel.FK_TBLHOPDO_RELATIONS_KHACHSAN", "TBLHOPDONG");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TBLHOPDONG>("QL_TourdulichModel.FK_TBLHOPDO_RELATIONS_KHACHSAN", "TBLHOPDONG", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QL_TourdulichModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QL_TourdulichModel", Name="TBLDIADANH")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBLDIADANH : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TBLDIADANH object.
        /// </summary>
        /// <param name="mADIADANH">Initial value of the MADIADANH property.</param>
        /// <param name="mADIADIEM">Initial value of the MADIADIEM property.</param>
        public static TBLDIADANH CreateTBLDIADANH(global::System.Int32 mADIADANH, global::System.String mADIADIEM)
        {
            TBLDIADANH tBLDIADANH = new TBLDIADANH();
            tBLDIADANH.MADIADANH = mADIADANH;
            tBLDIADANH.MADIADIEM = mADIADIEM;
            return tBLDIADANH;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MADIADANH
        {
            get
            {
                return _MADIADANH;
            }
            set
            {
                if (_MADIADANH != value)
                {
                    OnMADIADANHChanging(value);
                    ReportPropertyChanging("MADIADANH");
                    _MADIADANH = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MADIADANH");
                    OnMADIADANHChanged();
                }
            }
        }
        private global::System.Int32 _MADIADANH;
        partial void OnMADIADANHChanging(global::System.Int32 value);
        partial void OnMADIADANHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MADIADIEM
        {
            get
            {
                return _MADIADIEM;
            }
            set
            {
                OnMADIADIEMChanging(value);
                ReportPropertyChanging("MADIADIEM");
                _MADIADIEM = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MADIADIEM");
                OnMADIADIEMChanged();
            }
        }
        private global::System.String _MADIADIEM;
        partial void OnMADIADIEMChanging(global::System.String value);
        partial void OnMADIADIEMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TENDIADANH
        {
            get
            {
                return _TENDIADANH;
            }
            set
            {
                OnTENDIADANHChanging(value);
                ReportPropertyChanging("TENDIADANH");
                _TENDIADANH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TENDIADANH");
                OnTENDIADANHChanged();
            }
        }
        private global::System.String _TENDIADANH;
        partial void OnTENDIADANHChanging(global::System.String value);
        partial void OnTENDIADANHChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QL_TourdulichModel", "FK_TBLDIADA_RELATIONS_TBLDIADI", "TBLDIADIEM")]
        public TBLDIADIEM TBLDIADIEM
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLDIADIEM>("QL_TourdulichModel.FK_TBLDIADA_RELATIONS_TBLDIADI", "TBLDIADIEM").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLDIADIEM>("QL_TourdulichModel.FK_TBLDIADA_RELATIONS_TBLDIADI", "TBLDIADIEM").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TBLDIADIEM> TBLDIADIEMReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLDIADIEM>("QL_TourdulichModel.FK_TBLDIADA_RELATIONS_TBLDIADI", "TBLDIADIEM");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TBLDIADIEM>("QL_TourdulichModel.FK_TBLDIADA_RELATIONS_TBLDIADI", "TBLDIADIEM", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QL_TourdulichModel", Name="TBLDIADIEM")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBLDIADIEM : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TBLDIADIEM object.
        /// </summary>
        /// <param name="mADIADIEM">Initial value of the MADIADIEM property.</param>
        public static TBLDIADIEM CreateTBLDIADIEM(global::System.String mADIADIEM)
        {
            TBLDIADIEM tBLDIADIEM = new TBLDIADIEM();
            tBLDIADIEM.MADIADIEM = mADIADIEM;
            return tBLDIADIEM;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MADIADIEM
        {
            get
            {
                return _MADIADIEM;
            }
            set
            {
                if (_MADIADIEM != value)
                {
                    OnMADIADIEMChanging(value);
                    ReportPropertyChanging("MADIADIEM");
                    _MADIADIEM = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MADIADIEM");
                    OnMADIADIEMChanged();
                }
            }
        }
        private global::System.String _MADIADIEM;
        partial void OnMADIADIEMChanging(global::System.String value);
        partial void OnMADIADIEMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TENDIADIEM
        {
            get
            {
                return _TENDIADIEM;
            }
            set
            {
                OnTENDIADIEMChanging(value);
                ReportPropertyChanging("TENDIADIEM");
                _TENDIADIEM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TENDIADIEM");
                OnTENDIADIEMChanged();
            }
        }
        private global::System.String _TENDIADIEM;
        partial void OnTENDIADIEMChanging(global::System.String value);
        partial void OnTENDIADIEMChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QL_TourdulichModel", "FK_TBLDIADA_RELATIONS_TBLDIADI", "TBLDIADANH")]
        public EntityCollection<TBLDIADANH> TBLDIADANHs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TBLDIADANH>("QL_TourdulichModel.FK_TBLDIADA_RELATIONS_TBLDIADI", "TBLDIADANH");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TBLDIADANH>("QL_TourdulichModel.FK_TBLDIADA_RELATIONS_TBLDIADI", "TBLDIADANH", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QL_TourdulichModel", "CHITIETHANHTRINH", "TBLHANHTRINH")]
        public EntityCollection<TBLHANHTRINH> TBLHANHTRINHs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TBLHANHTRINH>("QL_TourdulichModel.CHITIETHANHTRINH", "TBLHANHTRINH");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TBLHANHTRINH>("QL_TourdulichModel.CHITIETHANHTRINH", "TBLHANHTRINH", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QL_TourdulichModel", Name="TBLHANHTRINH")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBLHANHTRINH : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TBLHANHTRINH object.
        /// </summary>
        /// <param name="mAHANHTRINH">Initial value of the MAHANHTRINH property.</param>
        public static TBLHANHTRINH CreateTBLHANHTRINH(global::System.Int32 mAHANHTRINH)
        {
            TBLHANHTRINH tBLHANHTRINH = new TBLHANHTRINH();
            tBLHANHTRINH.MAHANHTRINH = mAHANHTRINH;
            return tBLHANHTRINH;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MAHANHTRINH
        {
            get
            {
                return _MAHANHTRINH;
            }
            set
            {
                if (_MAHANHTRINH != value)
                {
                    OnMAHANHTRINHChanging(value);
                    ReportPropertyChanging("MAHANHTRINH");
                    _MAHANHTRINH = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MAHANHTRINH");
                    OnMAHANHTRINHChanged();
                }
            }
        }
        private global::System.Int32 _MAHANHTRINH;
        partial void OnMAHANHTRINHChanging(global::System.Int32 value);
        partial void OnMAHANHTRINHChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QL_TourdulichModel", "FK_TBLTOUR_RELATIONS_TBLHANHT", "TBLTOUR")]
        public EntityCollection<TBLTOUR> TBLTOURs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TBLTOUR>("QL_TourdulichModel.FK_TBLTOUR_RELATIONS_TBLHANHT", "TBLTOUR");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TBLTOUR>("QL_TourdulichModel.FK_TBLTOUR_RELATIONS_TBLHANHT", "TBLTOUR", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QL_TourdulichModel", "CHITIETHANHTRINH", "TBLDIADIEM")]
        public EntityCollection<TBLDIADIEM> TBLDIADIEMs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TBLDIADIEM>("QL_TourdulichModel.CHITIETHANHTRINH", "TBLDIADIEM");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TBLDIADIEM>("QL_TourdulichModel.CHITIETHANHTRINH", "TBLDIADIEM", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QL_TourdulichModel", Name="TBLHOPDONG")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBLHOPDONG : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TBLHOPDONG object.
        /// </summary>
        /// <param name="mAHOPDONG">Initial value of the MAHOPDONG property.</param>
        /// <param name="mAKHACHSAN">Initial value of the MAKHACHSAN property.</param>
        /// <param name="mAKHACHHANG">Initial value of the MAKHACHHANG property.</param>
        public static TBLHOPDONG CreateTBLHOPDONG(global::System.String mAHOPDONG, global::System.String mAKHACHSAN, global::System.String mAKHACHHANG)
        {
            TBLHOPDONG tBLHOPDONG = new TBLHOPDONG();
            tBLHOPDONG.MAHOPDONG = mAHOPDONG;
            tBLHOPDONG.MAKHACHSAN = mAKHACHSAN;
            tBLHOPDONG.MAKHACHHANG = mAKHACHHANG;
            return tBLHOPDONG;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MAHOPDONG
        {
            get
            {
                return _MAHOPDONG;
            }
            set
            {
                if (_MAHOPDONG != value)
                {
                    OnMAHOPDONGChanging(value);
                    ReportPropertyChanging("MAHOPDONG");
                    _MAHOPDONG = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MAHOPDONG");
                    OnMAHOPDONGChanged();
                }
            }
        }
        private global::System.String _MAHOPDONG;
        partial void OnMAHOPDONGChanging(global::System.String value);
        partial void OnMAHOPDONGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MAKHACHSAN
        {
            get
            {
                return _MAKHACHSAN;
            }
            set
            {
                OnMAKHACHSANChanging(value);
                ReportPropertyChanging("MAKHACHSAN");
                _MAKHACHSAN = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MAKHACHSAN");
                OnMAKHACHSANChanged();
            }
        }
        private global::System.String _MAKHACHSAN;
        partial void OnMAKHACHSANChanging(global::System.String value);
        partial void OnMAKHACHSANChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MAKHACHHANG
        {
            get
            {
                return _MAKHACHHANG;
            }
            set
            {
                OnMAKHACHHANGChanging(value);
                ReportPropertyChanging("MAKHACHHANG");
                _MAKHACHHANG = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MAKHACHHANG");
                OnMAKHACHHANGChanged();
            }
        }
        private global::System.String _MAKHACHHANG;
        partial void OnMAKHACHHANGChanging(global::System.String value);
        partial void OnMAKHACHHANGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SONGUOI
        {
            get
            {
                return _SONGUOI;
            }
            set
            {
                OnSONGUOIChanging(value);
                ReportPropertyChanging("SONGUOI");
                _SONGUOI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SONGUOI");
                OnSONGUOIChanged();
            }
        }
        private Nullable<global::System.Int32> _SONGUOI;
        partial void OnSONGUOIChanging(Nullable<global::System.Int32> value);
        partial void OnSONGUOIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NGAYDAT
        {
            get
            {
                return _NGAYDAT;
            }
            set
            {
                OnNGAYDATChanging(value);
                ReportPropertyChanging("NGAYDAT");
                _NGAYDAT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NGAYDAT");
                OnNGAYDATChanged();
            }
        }
        private Nullable<global::System.DateTime> _NGAYDAT;
        partial void OnNGAYDATChanging(Nullable<global::System.DateTime> value);
        partial void OnNGAYDATChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PHUTHU
        {
            get
            {
                return _PHUTHU;
            }
            set
            {
                OnPHUTHUChanging(value);
                ReportPropertyChanging("PHUTHU");
                _PHUTHU = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PHUTHU");
                OnPHUTHUChanged();
            }
        }
        private Nullable<global::System.Double> _PHUTHU;
        partial void OnPHUTHUChanging(Nullable<global::System.Double> value);
        partial void OnPHUTHUChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GHICHU
        {
            get
            {
                return _GHICHU;
            }
            set
            {
                OnGHICHUChanging(value);
                ReportPropertyChanging("GHICHU");
                _GHICHU = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GHICHU");
                OnGHICHUChanged();
            }
        }
        private global::System.String _GHICHU;
        partial void OnGHICHUChanging(global::System.String value);
        partial void OnGHICHUChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QL_TourdulichModel", "FK_TBLHOPDO_RELATIONS_KHACHSAN", "KHACHSAN")]
        public KHACHSAN KHACHSAN
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KHACHSAN>("QL_TourdulichModel.FK_TBLHOPDO_RELATIONS_KHACHSAN", "KHACHSAN").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KHACHSAN>("QL_TourdulichModel.FK_TBLHOPDO_RELATIONS_KHACHSAN", "KHACHSAN").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<KHACHSAN> KHACHSANReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KHACHSAN>("QL_TourdulichModel.FK_TBLHOPDO_RELATIONS_KHACHSAN", "KHACHSAN");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<KHACHSAN>("QL_TourdulichModel.FK_TBLHOPDO_RELATIONS_KHACHSAN", "KHACHSAN", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QL_TourdulichModel", "FK_TBLHOPDO_RELATIONS_TBLKHACH", "TBLKHACHHANG")]
        public TBLKHACHHANG TBLKHACHHANG
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLKHACHHANG>("QL_TourdulichModel.FK_TBLHOPDO_RELATIONS_TBLKHACH", "TBLKHACHHANG").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLKHACHHANG>("QL_TourdulichModel.FK_TBLHOPDO_RELATIONS_TBLKHACH", "TBLKHACHHANG").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TBLKHACHHANG> TBLKHACHHANGReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLKHACHHANG>("QL_TourdulichModel.FK_TBLHOPDO_RELATIONS_TBLKHACH", "TBLKHACHHANG");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TBLKHACHHANG>("QL_TourdulichModel.FK_TBLHOPDO_RELATIONS_TBLKHACH", "TBLKHACHHANG", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QL_TourdulichModel", "TBLCHIHOPDONG", "TBLTOUR")]
        public EntityCollection<TBLTOUR> TBLTOURs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TBLTOUR>("QL_TourdulichModel.TBLCHIHOPDONG", "TBLTOUR");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TBLTOUR>("QL_TourdulichModel.TBLCHIHOPDONG", "TBLTOUR", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QL_TourdulichModel", Name="TBLKHACHHANG")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBLKHACHHANG : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TBLKHACHHANG object.
        /// </summary>
        /// <param name="mAKHACHHANG">Initial value of the MAKHACHHANG property.</param>
        /// <param name="mALOAIKHACH">Initial value of the MALOAIKHACH property.</param>
        public static TBLKHACHHANG CreateTBLKHACHHANG(global::System.String mAKHACHHANG, global::System.String mALOAIKHACH)
        {
            TBLKHACHHANG tBLKHACHHANG = new TBLKHACHHANG();
            tBLKHACHHANG.MAKHACHHANG = mAKHACHHANG;
            tBLKHACHHANG.MALOAIKHACH = mALOAIKHACH;
            return tBLKHACHHANG;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MAKHACHHANG
        {
            get
            {
                return _MAKHACHHANG;
            }
            set
            {
                if (_MAKHACHHANG != value)
                {
                    OnMAKHACHHANGChanging(value);
                    ReportPropertyChanging("MAKHACHHANG");
                    _MAKHACHHANG = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MAKHACHHANG");
                    OnMAKHACHHANGChanged();
                }
            }
        }
        private global::System.String _MAKHACHHANG;
        partial void OnMAKHACHHANGChanging(global::System.String value);
        partial void OnMAKHACHHANGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MALOAIKHACH
        {
            get
            {
                return _MALOAIKHACH;
            }
            set
            {
                OnMALOAIKHACHChanging(value);
                ReportPropertyChanging("MALOAIKHACH");
                _MALOAIKHACH = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MALOAIKHACH");
                OnMALOAIKHACHChanged();
            }
        }
        private global::System.String _MALOAIKHACH;
        partial void OnMALOAIKHACHChanging(global::System.String value);
        partial void OnMALOAIKHACHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TENKHACHHANG
        {
            get
            {
                return _TENKHACHHANG;
            }
            set
            {
                OnTENKHACHHANGChanging(value);
                ReportPropertyChanging("TENKHACHHANG");
                _TENKHACHHANG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TENKHACHHANG");
                OnTENKHACHHANGChanged();
            }
        }
        private global::System.String _TENKHACHHANG;
        partial void OnTENKHACHHANGChanging(global::System.String value);
        partial void OnTENKHACHHANGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SEXKH
        {
            get
            {
                return _SEXKH;
            }
            set
            {
                OnSEXKHChanging(value);
                ReportPropertyChanging("SEXKH");
                _SEXKH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SEXKH");
                OnSEXKHChanged();
            }
        }
        private global::System.String _SEXKH;
        partial void OnSEXKHChanging(global::System.String value);
        partial void OnSEXKHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DCB
        {
            get
            {
                return _DCB;
            }
            set
            {
                OnDCBChanging(value);
                ReportPropertyChanging("DCB");
                _DCB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DCB");
                OnDCBChanged();
            }
        }
        private Nullable<global::System.DateTime> _DCB;
        partial void OnDCBChanging(Nullable<global::System.DateTime> value);
        partial void OnDCBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PHONE
        {
            get
            {
                return _PHONE;
            }
            set
            {
                OnPHONEChanging(value);
                ReportPropertyChanging("PHONE");
                _PHONE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PHONE");
                OnPHONEChanged();
            }
        }
        private Nullable<global::System.Int32> _PHONE;
        partial void OnPHONEChanging(Nullable<global::System.Int32> value);
        partial void OnPHONEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EMAIL
        {
            get
            {
                return _EMAIL;
            }
            set
            {
                OnEMAILChanging(value);
                ReportPropertyChanging("EMAIL");
                _EMAIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EMAIL");
                OnEMAILChanged();
            }
        }
        private global::System.String _EMAIL;
        partial void OnEMAILChanging(global::System.String value);
        partial void OnEMAILChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DIACHI
        {
            get
            {
                return _DIACHI;
            }
            set
            {
                OnDIACHIChanging(value);
                ReportPropertyChanging("DIACHI");
                _DIACHI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DIACHI");
                OnDIACHIChanged();
            }
        }
        private global::System.String _DIACHI;
        partial void OnDIACHIChanging(global::System.String value);
        partial void OnDIACHIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NGAYDANGKY
        {
            get
            {
                return _NGAYDANGKY;
            }
            set
            {
                OnNGAYDANGKYChanging(value);
                ReportPropertyChanging("NGAYDANGKY");
                _NGAYDANGKY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NGAYDANGKY");
                OnNGAYDANGKYChanged();
            }
        }
        private Nullable<global::System.DateTime> _NGAYDANGKY;
        partial void OnNGAYDANGKYChanging(Nullable<global::System.DateTime> value);
        partial void OnNGAYDANGKYChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QL_TourdulichModel", "FK_TBLHOPDO_RELATIONS_TBLKHACH", "TBLHOPDONG")]
        public EntityCollection<TBLHOPDONG> TBLHOPDONGs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TBLHOPDONG>("QL_TourdulichModel.FK_TBLHOPDO_RELATIONS_TBLKHACH", "TBLHOPDONG");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TBLHOPDONG>("QL_TourdulichModel.FK_TBLHOPDO_RELATIONS_TBLKHACH", "TBLHOPDONG", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QL_TourdulichModel", "FK_TBLKHACH_RELATIONS_TBLLOAIK", "TBLLOAIKHACH")]
        public TBLLOAIKHACH TBLLOAIKHACH
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLLOAIKHACH>("QL_TourdulichModel.FK_TBLKHACH_RELATIONS_TBLLOAIK", "TBLLOAIKHACH").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLLOAIKHACH>("QL_TourdulichModel.FK_TBLKHACH_RELATIONS_TBLLOAIK", "TBLLOAIKHACH").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TBLLOAIKHACH> TBLLOAIKHACHReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLLOAIKHACH>("QL_TourdulichModel.FK_TBLKHACH_RELATIONS_TBLLOAIK", "TBLLOAIKHACH");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TBLLOAIKHACH>("QL_TourdulichModel.FK_TBLKHACH_RELATIONS_TBLLOAIK", "TBLLOAIKHACH", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QL_TourdulichModel", Name="TBLLOAIKHACH")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBLLOAIKHACH : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TBLLOAIKHACH object.
        /// </summary>
        /// <param name="mALOAIKHACH">Initial value of the MALOAIKHACH property.</param>
        public static TBLLOAIKHACH CreateTBLLOAIKHACH(global::System.String mALOAIKHACH)
        {
            TBLLOAIKHACH tBLLOAIKHACH = new TBLLOAIKHACH();
            tBLLOAIKHACH.MALOAIKHACH = mALOAIKHACH;
            return tBLLOAIKHACH;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MALOAIKHACH
        {
            get
            {
                return _MALOAIKHACH;
            }
            set
            {
                if (_MALOAIKHACH != value)
                {
                    OnMALOAIKHACHChanging(value);
                    ReportPropertyChanging("MALOAIKHACH");
                    _MALOAIKHACH = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MALOAIKHACH");
                    OnMALOAIKHACHChanged();
                }
            }
        }
        private global::System.String _MALOAIKHACH;
        partial void OnMALOAIKHACHChanging(global::System.String value);
        partial void OnMALOAIKHACHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TENLOAIKHACH
        {
            get
            {
                return _TENLOAIKHACH;
            }
            set
            {
                OnTENLOAIKHACHChanging(value);
                ReportPropertyChanging("TENLOAIKHACH");
                _TENLOAIKHACH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TENLOAIKHACH");
                OnTENLOAIKHACHChanged();
            }
        }
        private global::System.String _TENLOAIKHACH;
        partial void OnTENLOAIKHACHChanging(global::System.String value);
        partial void OnTENLOAIKHACHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GHICHU
        {
            get
            {
                return _GHICHU;
            }
            set
            {
                OnGHICHUChanging(value);
                ReportPropertyChanging("GHICHU");
                _GHICHU = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GHICHU");
                OnGHICHUChanged();
            }
        }
        private global::System.String _GHICHU;
        partial void OnGHICHUChanging(global::System.String value);
        partial void OnGHICHUChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QL_TourdulichModel", "FK_TBLKHACH_RELATIONS_TBLLOAIK", "TBLKHACHHANG")]
        public EntityCollection<TBLKHACHHANG> TBLKHACHHANGs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TBLKHACHHANG>("QL_TourdulichModel.FK_TBLKHACH_RELATIONS_TBLLOAIK", "TBLKHACHHANG");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TBLKHACHHANG>("QL_TourdulichModel.FK_TBLKHACH_RELATIONS_TBLLOAIK", "TBLKHACHHANG", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QL_TourdulichModel", Name="TBLLOAIKHACHSAN")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBLLOAIKHACHSAN : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TBLLOAIKHACHSAN object.
        /// </summary>
        /// <param name="mALOAIKS">Initial value of the MALOAIKS property.</param>
        public static TBLLOAIKHACHSAN CreateTBLLOAIKHACHSAN(global::System.String mALOAIKS)
        {
            TBLLOAIKHACHSAN tBLLOAIKHACHSAN = new TBLLOAIKHACHSAN();
            tBLLOAIKHACHSAN.MALOAIKS = mALOAIKS;
            return tBLLOAIKHACHSAN;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MALOAIKS
        {
            get
            {
                return _MALOAIKS;
            }
            set
            {
                if (_MALOAIKS != value)
                {
                    OnMALOAIKSChanging(value);
                    ReportPropertyChanging("MALOAIKS");
                    _MALOAIKS = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MALOAIKS");
                    OnMALOAIKSChanged();
                }
            }
        }
        private global::System.String _MALOAIKS;
        partial void OnMALOAIKSChanging(global::System.String value);
        partial void OnMALOAIKSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TENLOAIKS
        {
            get
            {
                return _TENLOAIKS;
            }
            set
            {
                OnTENLOAIKSChanging(value);
                ReportPropertyChanging("TENLOAIKS");
                _TENLOAIKS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TENLOAIKS");
                OnTENLOAIKSChanged();
            }
        }
        private global::System.String _TENLOAIKS;
        partial void OnTENLOAIKSChanging(global::System.String value);
        partial void OnTENLOAIKSChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QL_TourdulichModel", "FK_KHACHSAN_RELATIONS_TBLLOAIK", "KHACHSAN")]
        public EntityCollection<KHACHSAN> KHACHSANs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<KHACHSAN>("QL_TourdulichModel.FK_KHACHSAN_RELATIONS_TBLLOAIK", "KHACHSAN");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<KHACHSAN>("QL_TourdulichModel.FK_KHACHSAN_RELATIONS_TBLLOAIK", "KHACHSAN", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QL_TourdulichModel", Name="TBLLOAITOUR")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBLLOAITOUR : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TBLLOAITOUR object.
        /// </summary>
        /// <param name="mALOAITOUR">Initial value of the MALOAITOUR property.</param>
        public static TBLLOAITOUR CreateTBLLOAITOUR(global::System.String mALOAITOUR)
        {
            TBLLOAITOUR tBLLOAITOUR = new TBLLOAITOUR();
            tBLLOAITOUR.MALOAITOUR = mALOAITOUR;
            return tBLLOAITOUR;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MALOAITOUR
        {
            get
            {
                return _MALOAITOUR;
            }
            set
            {
                if (_MALOAITOUR != value)
                {
                    OnMALOAITOURChanging(value);
                    ReportPropertyChanging("MALOAITOUR");
                    _MALOAITOUR = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MALOAITOUR");
                    OnMALOAITOURChanged();
                }
            }
        }
        private global::System.String _MALOAITOUR;
        partial void OnMALOAITOURChanging(global::System.String value);
        partial void OnMALOAITOURChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TENLOAITOUR
        {
            get
            {
                return _TENLOAITOUR;
            }
            set
            {
                OnTENLOAITOURChanging(value);
                ReportPropertyChanging("TENLOAITOUR");
                _TENLOAITOUR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TENLOAITOUR");
                OnTENLOAITOURChanged();
            }
        }
        private global::System.String _TENLOAITOUR;
        partial void OnTENLOAITOURChanging(global::System.String value);
        partial void OnTENLOAITOURChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QL_TourdulichModel", "FK_TBLTOUR_RELATIONS_TBLLOAIT", "TBLTOUR")]
        public EntityCollection<TBLTOUR> TBLTOURs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TBLTOUR>("QL_TourdulichModel.FK_TBLTOUR_RELATIONS_TBLLOAIT", "TBLTOUR");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TBLTOUR>("QL_TourdulichModel.FK_TBLTOUR_RELATIONS_TBLLOAIT", "TBLTOUR", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QL_TourdulichModel", Name="TBLTOUR")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBLTOUR : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TBLTOUR object.
        /// </summary>
        /// <param name="mATOUR">Initial value of the MATOUR property.</param>
        /// <param name="mAHANHTRINH">Initial value of the MAHANHTRINH property.</param>
        /// <param name="mALOAITOUR">Initial value of the MALOAITOUR property.</param>
        public static TBLTOUR CreateTBLTOUR(global::System.Int32 mATOUR, global::System.Int32 mAHANHTRINH, global::System.String mALOAITOUR)
        {
            TBLTOUR tBLTOUR = new TBLTOUR();
            tBLTOUR.MATOUR = mATOUR;
            tBLTOUR.MAHANHTRINH = mAHANHTRINH;
            tBLTOUR.MALOAITOUR = mALOAITOUR;
            return tBLTOUR;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MATOUR
        {
            get
            {
                return _MATOUR;
            }
            set
            {
                if (_MATOUR != value)
                {
                    OnMATOURChanging(value);
                    ReportPropertyChanging("MATOUR");
                    _MATOUR = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MATOUR");
                    OnMATOURChanged();
                }
            }
        }
        private global::System.Int32 _MATOUR;
        partial void OnMATOURChanging(global::System.Int32 value);
        partial void OnMATOURChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MAHANHTRINH
        {
            get
            {
                return _MAHANHTRINH;
            }
            set
            {
                OnMAHANHTRINHChanging(value);
                ReportPropertyChanging("MAHANHTRINH");
                _MAHANHTRINH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MAHANHTRINH");
                OnMAHANHTRINHChanged();
            }
        }
        private global::System.Int32 _MAHANHTRINH;
        partial void OnMAHANHTRINHChanging(global::System.Int32 value);
        partial void OnMAHANHTRINHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MALOAITOUR
        {
            get
            {
                return _MALOAITOUR;
            }
            set
            {
                OnMALOAITOURChanging(value);
                ReportPropertyChanging("MALOAITOUR");
                _MALOAITOUR = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MALOAITOUR");
                OnMALOAITOURChanged();
            }
        }
        private global::System.String _MALOAITOUR;
        partial void OnMALOAITOURChanging(global::System.String value);
        partial void OnMALOAITOURChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TENTOUR
        {
            get
            {
                return _TENTOUR;
            }
            set
            {
                OnTENTOURChanging(value);
                ReportPropertyChanging("TENTOUR");
                _TENTOUR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TENTOUR");
                OnTENTOURChanged();
            }
        }
        private global::System.String _TENTOUR;
        partial void OnTENTOURChanging(global::System.String value);
        partial void OnTENTOURChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TRANGTHAI
        {
            get
            {
                return _TRANGTHAI;
            }
            set
            {
                OnTRANGTHAIChanging(value);
                ReportPropertyChanging("TRANGTHAI");
                _TRANGTHAI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TRANGTHAI");
                OnTRANGTHAIChanged();
            }
        }
        private Nullable<global::System.Int32> _TRANGTHAI;
        partial void OnTRANGTHAIChanging(Nullable<global::System.Int32> value);
        partial void OnTRANGTHAIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> GIATOUR
        {
            get
            {
                return _GIATOUR;
            }
            set
            {
                OnGIATOURChanging(value);
                ReportPropertyChanging("GIATOUR");
                _GIATOUR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GIATOUR");
                OnGIATOURChanged();
            }
        }
        private Nullable<global::System.Double> _GIATOUR;
        partial void OnGIATOURChanging(Nullable<global::System.Double> value);
        partial void OnGIATOURChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NGAYKHOIHANH
        {
            get
            {
                return _NGAYKHOIHANH;
            }
            set
            {
                OnNGAYKHOIHANHChanging(value);
                ReportPropertyChanging("NGAYKHOIHANH");
                _NGAYKHOIHANH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NGAYKHOIHANH");
                OnNGAYKHOIHANHChanged();
            }
        }
        private Nullable<global::System.DateTime> _NGAYKHOIHANH;
        partial void OnNGAYKHOIHANHChanging(Nullable<global::System.DateTime> value);
        partial void OnNGAYKHOIHANHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NGAYKETTHUC
        {
            get
            {
                return _NGAYKETTHUC;
            }
            set
            {
                OnNGAYKETTHUCChanging(value);
                ReportPropertyChanging("NGAYKETTHUC");
                _NGAYKETTHUC = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NGAYKETTHUC");
                OnNGAYKETTHUCChanged();
            }
        }
        private Nullable<global::System.DateTime> _NGAYKETTHUC;
        partial void OnNGAYKETTHUCChanging(Nullable<global::System.DateTime> value);
        partial void OnNGAYKETTHUCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HINHANH
        {
            get
            {
                return _HINHANH;
            }
            set
            {
                OnHINHANHChanging(value);
                ReportPropertyChanging("HINHANH");
                _HINHANH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HINHANH");
                OnHINHANHChanged();
            }
        }
        private global::System.String _HINHANH;
        partial void OnHINHANHChanging(global::System.String value);
        partial void OnHINHANHChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QL_TourdulichModel", "FK_TBLTOUR_RELATIONS_TBLHANHT", "TBLHANHTRINH")]
        public TBLHANHTRINH TBLHANHTRINH
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLHANHTRINH>("QL_TourdulichModel.FK_TBLTOUR_RELATIONS_TBLHANHT", "TBLHANHTRINH").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLHANHTRINH>("QL_TourdulichModel.FK_TBLTOUR_RELATIONS_TBLHANHT", "TBLHANHTRINH").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TBLHANHTRINH> TBLHANHTRINHReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLHANHTRINH>("QL_TourdulichModel.FK_TBLTOUR_RELATIONS_TBLHANHT", "TBLHANHTRINH");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TBLHANHTRINH>("QL_TourdulichModel.FK_TBLTOUR_RELATIONS_TBLHANHT", "TBLHANHTRINH", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QL_TourdulichModel", "FK_TBLTOUR_RELATIONS_TBLLOAIT", "TBLLOAITOUR")]
        public TBLLOAITOUR TBLLOAITOUR
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLLOAITOUR>("QL_TourdulichModel.FK_TBLTOUR_RELATIONS_TBLLOAIT", "TBLLOAITOUR").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLLOAITOUR>("QL_TourdulichModel.FK_TBLTOUR_RELATIONS_TBLLOAIT", "TBLLOAITOUR").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TBLLOAITOUR> TBLLOAITOURReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLLOAITOUR>("QL_TourdulichModel.FK_TBLTOUR_RELATIONS_TBLLOAIT", "TBLLOAITOUR");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TBLLOAITOUR>("QL_TourdulichModel.FK_TBLTOUR_RELATIONS_TBLLOAIT", "TBLLOAITOUR", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QL_TourdulichModel", "TBLCHIHOPDONG", "TBLHOPDONG")]
        public EntityCollection<TBLHOPDONG> TBLHOPDONGs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TBLHOPDONG>("QL_TourdulichModel.TBLCHIHOPDONG", "TBLHOPDONG");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TBLHOPDONG>("QL_TourdulichModel.TBLCHIHOPDONG", "TBLHOPDONG", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
