//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDIADIEM
    {
        public TBLDIADIEM()
        {
            this.TBLDIADANHs = new HashSet<TBLDIADANH>();
            this.TBLHANHTRINHs = new HashSet<TBLHANHTRINH>();
        }
    
        public string MADIADIEM { get; set; }
        public string TENDIADIEM { get; set; }
    
        public virtual ICollection<TBLDIADANH> TBLDIADANHs { get; set; }
        public virtual ICollection<TBLHANHTRINH> TBLHANHTRINHs { get; set; }
    }
}
