//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDIADANH
    {
        public int MADIADANH { get; set; }
        public string MADIADIEM { get; set; }
        public string TENDIADANH { get; set; }
    
        public virtual TBLDIADIEM TBLDIADIEM { get; set; }
    }
}
