//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHANHTRINH
    {
        public TBLHANHTRINH()
        {
            this.TBLTOURs = new HashSet<TBLTOUR>();
            this.TBLDIADIEMs = new HashSet<TBLDIADIEM>();
        }
    
        public int MAHANHTRINH { get; set; }
    
        public virtual ICollection<TBLTOUR> TBLTOURs { get; set; }
        public virtual ICollection<TBLDIADIEM> TBLDIADIEMs { get; set; }
    }
}
