//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHOPDONG
    {
        public TBLHOPDONG()
        {
            this.TBLTOURs = new HashSet<TBLTOUR>();
        }
    
        public string MAHOPDONG { get; set; }
        public string MAKHACHSAN { get; set; }
        public string MAKHACHHANG { get; set; }
        public Nullable<int> SONGUOI { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<double> PHUTHU { get; set; }
        public string GHICHU { get; set; }
    
        public virtual KHACHSAN KHACHSAN { get; set; }
        public virtual TBLKHACHHANG TBLKHACHHANG { get; set; }
        public virtual ICollection<TBLTOUR> TBLTOURs { get; set; }
    }
}
