//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKHACHHANG
    {
        public TBLKHACHHANG()
        {
            this.TBLHOPDONGs = new HashSet<TBLHOPDONG>();
        }
    
        public string MAKHACHHANG { get; set; }
        public string MALOAIKHACH { get; set; }
        public string TENKHACHHANG { get; set; }
        public string SEXKH { get; set; }
        public Nullable<System.DateTime> DCB { get; set; }
        public Nullable<int> PHONE { get; set; }
        public string EMAIL { get; set; }
        public string DIACHI { get; set; }
        public Nullable<System.DateTime> NGAYDANGKY { get; set; }
    
        public virtual ICollection<TBLHOPDONG> TBLHOPDONGs { get; set; }
        public virtual TBLLOAIKHACH TBLLOAIKHACH { get; set; }
    }
}
