//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLLOAITOUR
    {
        public TBLLOAITOUR()
        {
            this.TBLTOURs = new HashSet<TBLTOUR>();
        }
    
        public string MALOAITOUR { get; set; }
        public string TENLOAITOUR { get; set; }
    
        public virtual ICollection<TBLTOUR> TBLTOURs { get; set; }
    }
}
