//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLLOAIKHACH
    {
        public TBLLOAIKHACH()
        {
            this.TBLKHACHHANGs = new HashSet<TBLKHACHHANG>();
        }
    
        public string MALOAIKHACH { get; set; }
        public string TENLOAIKHACH { get; set; }
        public string GHICHU { get; set; }
    
        public virtual ICollection<TBLKHACHHANG> TBLKHACHHANGs { get; set; }
    }
}
