//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOUR()
        {
            this.CHITIETHOPDONGs = new HashSet<CHITIETHOPDONG>();
        }
    
        public string MATOUR { get; set; }
        public string MALOAITOUR { get; set; }
        public string MAHANTRINH { get; set; }
        public decimal GIATOUR { get; set; }
        public System.DateTime NGAYKHOIHANH { get; set; }
        public System.DateTime NGAYKETTHUC { get; set; }
        public byte[] HINHANH { get; set; }
        public string MOTA { get; set; }
        public string TENTOUR { get; set; }
        public Nullable<decimal> GIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOPDONG> CHITIETHOPDONGs { get; set; }
        public virtual HANHTRINH HANHTRINH { get; set; }
        public virtual LOAITOUR LOAITOUR { get; set; }
    }
}
